"""add_scheduling_to_course_sections

Revision ID: 37f74eb2b954
Revises: 202606290000
Create Date: 2026-06-30 01:05:03.333196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37f74eb2b954'
down_revision: Union[str, None] = '202606290000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_sections', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('course_sections', sa.Column('end_date', sa.Date(), nullable=True))
    op.add_column('course_sections', sa.Column('class_time', sa.Time(), nullable=True))
    op.add_column('course_sections', sa.Column('class_duration_minutes', sa.Integer(), nullable=True))
    op.add_column('course_sections', sa.Column('classroom', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course_sections', 'classroom')
    op.drop_column('course_sections', 'class_duration_minutes')
    op.drop_column('course_sections', 'class_time')
    op.drop_column('course_sections', 'end_date')
    op.drop_column('course_sections', 'start_date')
    # ### end Alembic commands ###
