"""add_compensation_contract_ledger

Revision ID: e37ad410e0e2
Revises: 202607070001
Create Date: 2026-07-08 03:15:16.349213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e37ad410e0e2'
down_revision: Union[str, None] = '202607070001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('section_contracts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=True),
    sa.Column('compensation_model', sa.Enum('fixed', 'percentage', name='compensationmodel', create_constraint=True), nullable=True),
    sa.Column('fixed_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('holdback_rate', sa.Numeric(precision=5, scale=4), server_default=sa.text('0.20'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'assigned', 'active', 'grades_submitted', 'settled', 'cancelled', name='contractstatus', create_constraint=True), server_default='draft', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc'::text, now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc'::text, now())"), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['course_sections.id'], name=op.f('fk_section_contracts_section_id_course_sections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['employees.id'], name=op.f('fk_section_contracts_teacher_id_employees'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_section_contracts')),
    sa.UniqueConstraint('section_id', name=op.f('uq_section_contracts_section_id'))
    )
    op.create_index(op.f('ix_section_contracts_teacher_id'), 'section_contracts', ['teacher_id'], unique=False)
    op.create_table('ledger_entries',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('activation_credit', 'payment_share', 'grade_unfreeze', 'amendment_adjustment', 'reversal', 'withdrawal', name='ledgerentrytype', create_constraint=True), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('available_delta', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('frozen_delta', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reference_type', sa.String(length=20), nullable=True),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc'::text, now())"), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['section_contracts.id'], name=op.f('fk_ledger_entries_contract_id_section_contracts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_ledger_entries_created_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['wallet_id'], ['teacher_wallets.id'], name=op.f('fk_ledger_entries_wallet_id_teacher_wallets'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger_entries'))
    )
    op.create_index(op.f('ix_ledger_entries_contract_id'), 'ledger_entries', ['contract_id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_created_by'), 'ledger_entries', ['created_by'], unique=False)
    op.create_index(op.f('ix_ledger_entries_wallet_id'), 'ledger_entries', ['wallet_id'], unique=False)
    op.create_table('compensation_amendment_requests',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('previous_fixed_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('requested_fixed_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('previous_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('requested_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('requested_by', sa.UUID(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc'::text, now())"), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='amendmentstatus', create_constraint=True), server_default='pending', nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('ledger_entry_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['section_contracts.id'], name=op.f('fk_compensation_amendment_requests_contract_id_section_contracts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ledger_entry_id'], ['ledger_entries.id'], name=op.f('fk_compensation_amendment_requests_ledger_entry_id_ledger_entries'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by'], ['employees.id'], name=op.f('fk_compensation_amendment_requests_requested_by_employees'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['employees.id'], name=op.f('fk_compensation_amendment_requests_reviewed_by_employees'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compensation_amendment_requests'))
    )
    op.create_index(op.f('ix_compensation_amendment_requests_contract_id'), 'compensation_amendment_requests', ['contract_id'], unique=False)
    op.create_index(op.f('ix_compensation_amendment_requests_requested_by'), 'compensation_amendment_requests', ['requested_by'], unique=False)
    op.create_index(op.f('ix_compensation_amendment_requests_reviewed_by'), 'compensation_amendment_requests', ['reviewed_by'], unique=False)
    op.drop_index('idx_assignments_section_id', table_name='assignments')
    op.create_index(op.f('ix_assignments_section_id'), 'assignments', ['section_id'], unique=False)
    op.drop_index('idx_attendance_records_session_id', table_name='attendance_records')
    op.drop_index('idx_attendance_records_student_id', table_name='attendance_records')
    op.create_index(op.f('ix_attendance_records_session_id'), 'attendance_records', ['session_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_student_id'), 'attendance_records', ['student_id'], unique=False)
    op.drop_index('idx_attendance_sessions_created_by', table_name='attendance_sessions')
    op.drop_index('idx_attendance_sessions_section_id', table_name='attendance_sessions')
    op.create_index(op.f('ix_attendance_sessions_created_by'), 'attendance_sessions', ['created_by'], unique=False)
    op.create_index(op.f('ix_attendance_sessions_section_id'), 'attendance_sessions', ['section_id'], unique=False)
    op.drop_index('idx_audit_logs_user_id', table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.alter_column('course_sections', 'teacher_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index('idx_course_sections_course_id', table_name='course_sections')
    op.drop_index('idx_course_sections_teacher_id', table_name='course_sections')
    op.create_index(op.f('ix_course_sections_course_id'), 'course_sections', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_sections_teacher_id'), 'course_sections', ['teacher_id'], unique=False)
    # Rename unique constraints from postgres-default names to naming-convention
    # names. Both styles may exist depending on when the DB was created, so
    # drop whichever is present before creating the convention-named one.
    op.execute("ALTER TABLE courses DROP CONSTRAINT IF EXISTS courses_code_key")
    op.execute("ALTER TABLE courses DROP CONSTRAINT IF EXISTS uq_courses_code")
    op.drop_index('idx_daily_closures_closed_by_manager_id', table_name='daily_closures')
    op.create_index(op.f('ix_daily_closures_closed_by_manager_id'), 'daily_closures', ['closed_by_manager_id'], unique=False)
    op.add_column('employees', sa.Column('default_salary', sa.Numeric(precision=12, scale=2), nullable=True))
    op.drop_column('employees', 'salary')
    op.drop_column('employees', 'compensation_type')
    op.drop_index('idx_enrollments_section_id', table_name='enrollments')
    op.drop_index('idx_enrollments_student_id', table_name='enrollments')
    op.create_index(op.f('ix_enrollments_section_id'), 'enrollments', ['section_id'], unique=False)
    op.create_index(op.f('ix_enrollments_student_id'), 'enrollments', ['student_id'], unique=False)
    op.execute("ALTER TABLE expenses DROP CONSTRAINT IF EXISTS expenses_receipt_number_key")
    op.execute("ALTER TABLE expenses DROP CONSTRAINT IF EXISTS uq_expenses_receipt_number")
    op.drop_index('idx_expenses_recipient_id', table_name='expenses')
    op.create_index(op.f('ix_expenses_recipient_id'), 'expenses', ['recipient_id'], unique=False)
    op.execute("ALTER TABLE grades DROP CONSTRAINT IF EXISTS grades_submission_id_key")
    op.execute("ALTER TABLE grades DROP CONSTRAINT IF EXISTS uq_grades_submission_id")
    op.drop_index('idx_grades_graded_by', table_name='grades')
    op.create_index(op.f('ix_grades_graded_by'), 'grades', ['graded_by'], unique=False)
    op.create_unique_constraint(op.f('uq_grades_submission_id'), 'grades', ['submission_id'])
    op.drop_index('idx_payments_enrollment_id', table_name='payments')
    op.execute("ALTER TABLE payments DROP CONSTRAINT IF EXISTS payments_receipt_number_key")
    op.execute("ALTER TABLE payments DROP CONSTRAINT IF EXISTS uq_payments_receipt_number")
    op.create_index(op.f('ix_payments_enrollment_id'), 'payments', ['enrollment_id'], unique=False)
    op.drop_index('idx_refresh_tokens_expires_at', table_name='refresh_tokens')
    op.drop_index('idx_refresh_tokens_user_id', table_name='refresh_tokens')
    op.create_index(op.f('ix_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.execute("ALTER TABLE students DROP CONSTRAINT IF EXISTS students_student_code_key")
    op.execute("ALTER TABLE students DROP CONSTRAINT IF EXISTS uq_students_student_code")
    op.drop_index('idx_submissions_assignment_id', table_name='submissions')
    op.drop_index('idx_submissions_student_id', table_name='submissions')
    op.create_index(op.f('ix_submissions_assignment_id'), 'submissions', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_submissions_student_id'), 'submissions', ['student_id'], unique=False)
    op.add_column('teacher_wallets', sa.Column('frozen_balance', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False))
    op.execute("ALTER TABLE teacher_wallets DROP CONSTRAINT IF EXISTS teacher_wallets_teacher_id_key")
    op.execute("ALTER TABLE teacher_wallets DROP CONSTRAINT IF EXISTS uq_teacher_wallets_teacher_id")
    op.create_unique_constraint(op.f('uq_teacher_wallets_teacher_id'), 'teacher_wallets', ['teacher_id'])
    op.drop_index('idx_users_employee_id', table_name='users')
    op.drop_index('idx_users_role_id', table_name='users')
    op.create_index(op.f('ix_users_employee_id'), 'users', ['employee_id'], unique=False)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_employee_id'), table_name='users')
    op.create_index('idx_users_role_id', 'users', ['role_id'], unique=False)
    op.create_index('idx_users_employee_id', 'users', ['employee_id'], unique=False)
    op.drop_constraint(op.f('uq_teacher_wallets_teacher_id'), 'teacher_wallets', type_='unique')
    op.create_unique_constraint('teacher_wallets_teacher_id_key', 'teacher_wallets', ['teacher_id'])
    op.drop_column('teacher_wallets', 'frozen_balance')
    op.drop_index(op.f('ix_submissions_student_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_assignment_id'), table_name='submissions')
    op.create_index('idx_submissions_student_id', 'submissions', ['student_id'], unique=False)
    op.create_index('idx_submissions_assignment_id', 'submissions', ['assignment_id'], unique=False)
    op.create_unique_constraint('students_student_code_key', 'students', ['student_code'])
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_expires_at'), table_name='refresh_tokens')
    op.create_index('idx_refresh_tokens_user_id', 'refresh_tokens', ['user_id'], unique=False)
    op.create_index('idx_refresh_tokens_expires_at', 'refresh_tokens', ['expires_at'], unique=False)
    op.drop_index(op.f('ix_payments_enrollment_id'), table_name='payments')
    op.create_unique_constraint('payments_receipt_number_key', 'payments', ['receipt_number'])
    op.create_index('idx_payments_enrollment_id', 'payments', ['enrollment_id'], unique=False)
    op.drop_constraint(op.f('uq_grades_submission_id'), 'grades', type_='unique')
    op.drop_index(op.f('ix_grades_graded_by'), table_name='grades')
    op.create_index('idx_grades_graded_by', 'grades', ['graded_by'], unique=False)
    op.create_unique_constraint('grades_submission_id_key', 'grades', ['submission_id'])
    op.drop_index(op.f('ix_expenses_recipient_id'), table_name='expenses')
    op.create_index('idx_expenses_recipient_id', 'expenses', ['recipient_id'], unique=False)
    op.create_unique_constraint('expenses_receipt_number_key', 'expenses', ['receipt_number'])
    op.drop_index(op.f('ix_enrollments_student_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_section_id'), table_name='enrollments')
    op.create_index('idx_enrollments_student_id', 'enrollments', ['student_id'], unique=False)
    op.create_index('idx_enrollments_section_id', 'enrollments', ['section_id'], unique=False)
    op.add_column('employees', sa.Column('compensation_type', postgresql.ENUM('salary', 'percentage', 'hybrid', name='compensationtype'), server_default=sa.text("'salary'::compensationtype"), autoincrement=False, nullable=False))
    op.add_column('employees', sa.Column('salary', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.drop_column('employees', 'default_salary')
    op.drop_index(op.f('ix_daily_closures_closed_by_manager_id'), table_name='daily_closures')
    op.create_index('idx_daily_closures_closed_by_manager_id', 'daily_closures', ['closed_by_manager_id'], unique=False)
    op.create_unique_constraint('courses_code_key', 'courses', ['code'])
    op.drop_index(op.f('ix_course_sections_teacher_id'), table_name='course_sections')
    op.drop_index(op.f('ix_course_sections_course_id'), table_name='course_sections')
    op.create_index('idx_course_sections_teacher_id', 'course_sections', ['teacher_id'], unique=False)
    op.create_index('idx_course_sections_course_id', 'course_sections', ['course_id'], unique=False)
    op.alter_column('course_sections', 'teacher_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.create_index('idx_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.drop_index(op.f('ix_attendance_sessions_section_id'), table_name='attendance_sessions')
    op.drop_index(op.f('ix_attendance_sessions_created_by'), table_name='attendance_sessions')
    op.create_index('idx_attendance_sessions_section_id', 'attendance_sessions', ['section_id'], unique=False)
    op.create_index('idx_attendance_sessions_created_by', 'attendance_sessions', ['created_by'], unique=False)
    op.drop_index(op.f('ix_attendance_records_student_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_session_id'), table_name='attendance_records')
    op.create_index('idx_attendance_records_student_id', 'attendance_records', ['student_id'], unique=False)
    op.create_index('idx_attendance_records_session_id', 'attendance_records', ['session_id'], unique=False)
    op.drop_index(op.f('ix_assignments_section_id'), table_name='assignments')
    op.create_index('idx_assignments_section_id', 'assignments', ['section_id'], unique=False)
    op.drop_index(op.f('ix_compensation_amendment_requests_reviewed_by'), table_name='compensation_amendment_requests')
    op.drop_index(op.f('ix_compensation_amendment_requests_requested_by'), table_name='compensation_amendment_requests')
    op.drop_index(op.f('ix_compensation_amendment_requests_contract_id'), table_name='compensation_amendment_requests')
    op.drop_table('compensation_amendment_requests')
    op.drop_index(op.f('ix_ledger_entries_wallet_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_created_by'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_contract_id'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_index(op.f('ix_section_contracts_teacher_id'), table_name='section_contracts')
    op.drop_table('section_contracts')
    # ### end Alembic commands ###
