export const landingDefaults = {
  ar: {
    navAI: "الذكاء الاصطلاحي",
    navPrograms: "البرامج",
    navAteliers: "الورش",
    navCampus: "الحرم",
    navContact: "العنوان",
    staffLogin: "دخول الكادر",
    liveLabel: "مباشر من الحرم",
    liveCardTitle: "جدول اليوم",
    levels: ["A1", "A2", "B1", "B2", "C1", "C2"] as string[],
    lang: "English",
    heroKicker: "مستوى واحد في كل مرة",
    heroLine1: "تتعلّم",
    heroLine2: "بمساعدة الذكاء الإصطناعي",
    heroLine3: "وتطبّق في نفس اليوم.",
    heroDesc: "فصول 8 طلاب، مختبر يومي، ومساعد ذكاء اصطناعي يرافقك — يصحح نطقك، يراجع كودك، ويبني لك خطة مراجعة. في تعز منذ 1998، بعقل جديد.",
    ctaPrimary: "احجز مقعد مجاني →",
    ctaGhost: "شاهد البرامج",
    micro: "التسجيل حضوري فقط · اختبار تحديد مستوى مجاني · واتساب للرد السريع",
    programsEyebrow: "البرامج",
    programsTitle: "اختر ما تريد أن تتقنه",
    programsSub: "قائمة مفتوحة — نضيف مسارات جديدة كل فصل. كل برنامج له ورشة، مشروع، وشهادة QR قابلة للتحقق.",
    programs: [
      { id: "languages", k: "اللغات", d: "محادثة يومية ومخبر صوتي — من الحروف إلى المناظرة.", meta: "A1 → C2", outcome: "IELTS 6+ / محادثة بطلاقة", duration: "12 أسبوع", intake: "24 أغسطس", seats: "8 مقاعد متبقية", priceHint: "أقساط شهرية" },
      { id: "computing", k: "علوم الحاسب", d: "بايثون، قواعد بيانات، شبكات وويب — تبني شيئًا يعمل كل أسبوع.", meta: "12 مساقًا", outcome: "مطور Junior + بورتفوليو", duration: "16 أسبوع", intake: "1 سبتمبر", seats: "5 مقاعد متبقية", priceHint: "مشروع تخرج" },
      { id: "ai", k: "الذكاء الاصطناعي", d: "أساسيات عملية — أدوات، بيانات، ومشاريع يمكنك عرضها.", meta: "جديد", outcome: "مساعد AI جاهز للعرض", duration: "10 أسابيع", intake: "7 سبتمبر", seats: "12 مقعدًا", priceHint: "للمبتدئين" },
      { id: "diplomas", k: "الدبلومات", d: "محاسبة وإدارة وسكرتارية — حالات واقعية وملف إنجاز.", meta: "180 ساعة", outcome: "جاهز للتوظيف", duration: "6 أشهر", intake: "15 أغسطس", seats: "مقاعد محدودة", priceHint: "شهادة QR" },
    ],
    ateliersTitle: "الورش — حيث يحدث التعلّم",
    ateliers: [
      { k: "مختبر الصوت", v: "60 دقيقة يوميًا", p: "سماعات، تسجيل، وتصحيح نطق فوري. تتكلم أكثر مما تكتب." },
      { k: "مختبر الكود", v: "حاسوب لكل طالب", p: "بيئة حقيقية، سيرفر محلي، ومشروع يُرفع على رابط." },
      { k: "ورشة الأعمال", v: "حالات واقعية", p: "فواتير، ميزانيات، ومراسلات — كما في الشركة." },
    ],
    stats: [
      { value: "1998→", label: "28 سنة في تعز" },
      { value: "12k+", label: "خريج" },
      { value: "4.8/5", label: "تقييم Google" },
      { value: "8", label: "طلاب max / فصل" },
    ],
    testimonials: [
      { name: "سارة أحمد", track: "لغات — B2", quote: "من A1 إلى عرض تقديمي بالإنجليزية في 4 أشهر. المختبر الصوتي فرق معي.", rating: 5 },
      { name: "كرم عبده", track: "حاسب — بايثون", quote: "كل أسبوع مشروع شغال. الآن عندي بورتفوليو أقدّمه للشركات.", rating: 5 },
      { name: "نورا سعيد", track: "دبلوم محاسبة", quote: "حالات حقيقية ودفتر عملي — توظفت قبل ما أكمّل.", rating: 5 },
    ],
    faqTitle: "أسئلة تتكرر",
    faqSub: "لو بقي سؤال، راسلنا واتساب — نرد خلال ساعات.",
    faqs: [
      { q: "كم الرسوم؟ هل يوجد تقسيط؟", a: "الرسوم حسب المسار والمستوى. يوجد تقسيط شهري بدون فوائد — اسأل عند اختبار المستوى المجاني." },
      { q: "هل توجد فترات للنساء؟", a: "نعم، فترات صباحية ومسائية منفصلة، وقاعات مجهزة. اسألي عن الجدول عند الحجز." },
      { q: "هل الشهادة معتمدة؟", a: "نعم، كل شهادة عليها QR يتحقق منها صاحب العمل فورًا — مع ملف إنجاز/بورتفوليو." },
      { q: "هل تساعدوني في التوظيف؟", a: "نراجع سيرتك، نجهز بورتفوليو، ونشارك فرص شركائنا في تعز وعدن والعمل عن بُعد." },
      { q: "هل أحتاج لابتوب؟", a: "لا. كل طالب له حاسوب في مختبر الكود. فقط تجي وتطبّق." },
    ],
    contactTitle: "تعال وشاهد حصة",
    address: "تعز — اليمن — معهد الدراسات",
    hours: "السبت – الخميس · 08:30 — 19:30",
    phone: "04 — 123 456",
    footer: "© معهد الدراسات — تعز. التسجيل حضوري.",
  },
  en: {
    navAI: "AI",
    navPrograms: "Programs",
    navAteliers: "Ateliers",
    navCampus: "Campus",
    navContact: "Visit",
    staffLogin: "Staff login",
    liveLabel: "Live from campus",
    liveCardTitle: "Today",
    levels: ["A1", "A2", "B1", "B2", "C1", "C2"] as string[],
    lang: "العربية",
    heroKicker: "One level at a time",
    heroLine1: "Learn it",
    heroLine2: "with AI",
    heroLine3: "ship it same day.",
    heroDesc: "8 max per section, daily lab, QR-verifiable certificate — plus an AI companion that tunes your pronunciation, reviews your code, and builds your revision plan. Since 1998, now AI-forward.",
    ctaPrimary: "Book free trial →",
    ctaGhost: "See programs",
    micro: "On-campus enrolment · Free placement test · WhatsApp reply in hours",
    programsEyebrow: "Programs",
    programsTitle: "Choose what you want to master",
    programsSub: "Open list — we add tracks each term. Every program has an atelier, a project, and a verifiable certificate.",
    programs: [
      { id: "languages", k: "Languages", d: "Daily conversation & audio lab — letters to debate.", meta: "A1 → C2", outcome: "IELTS 6+ / Fluent talk", duration: "12 weeks", intake: "24 Aug", seats: "8 seats left", priceHint: "Monthly plan" },
      { id: "computing", k: "Computing", d: "Python, DB, networks & web — ship something every week.", meta: "12 courses", outcome: "Junior dev + portfolio", duration: "16 weeks", intake: "1 Sep", seats: "5 left", priceHint: "Capstone project" },
      { id: "ai", k: "Artificial Intelligence", d: "Practical AI — tools, data and projects you can demo.", meta: "New", outcome: "Demo-ready AI assistant", duration: "10 weeks", intake: "7 Sep", seats: "12 seats", priceHint: "Beginner-friendly" },
      { id: "diplomas", k: "Diplomas", d: "Accounting, management, secretarial — real cases & portfolio.", meta: "180 hrs", outcome: "Job-ready", duration: "6 months", intake: "15 Aug", seats: "Limited", priceHint: "QR certificate" },
    ],
    ateliersTitle: "Ateliers — where learning happens",
    ateliers: [
      { k: "Sound Lab", v: "60 min daily", p: "Headsets, recording, instant correction. You speak more than you write." },
      { k: "Code Lab", v: "1 machine per student", p: "Real env, local server, deploy link for your project." },
      { k: "Business Atelier", v: "Real cases", p: "Invoices, budgets, letters — as in a company." },
    ],
    stats: [
      { value: "1998→", label: "28 years in Taiz" },
      { value: "12k+", label: "graduates" },
      { value: "4.8/5", label: "Google rating" },
      { value: "8", label: "max / class" },
    ],
    testimonials: [
      { name: "Sara Ahmed", track: "Languages — B2", quote: "From A1 to presenting in English in 4 months. The sound lab changed everything.", rating: 5 },
      { name: "Karam Abdo", track: "Computing — Python", quote: "Shipped a project every week. Now I have a portfolio to show employers.", rating: 5 },
      { name: "Nora Said", track: "Diploma — Accounting", quote: "Real cases and a hands-on ledger — got hired before I finished.", rating: 5 },
    ],
    faqTitle: "Good questions",
    faqSub: "Still unsure? WhatsApp us — we reply within hours.",
    faqs: [
      { q: "How much? Installments?", a: "Depends on track & level. Monthly installments, no interest — ask at your free placement test." },
      { q: "Women-only sessions?", a: "Yes — separate morning & evening slots with dedicated rooms. Ask when you book." },
      { q: "Is the certificate verifiable?", a: "Yes — every certificate has a QR that employers can verify instantly, plus your portfolio." },
      { q: "Job help?", a: "We review your CV, polish your portfolio, and share opportunities from our partners in Taiz, Aden & remote." },
      { q: "Do I need a laptop?", a: "No. Every student gets a machine in the Code Lab. Just show up and build." },
    ],
    contactTitle: "Come watch a class",
    address: "Taiz — Yemen — Al-Drasat Institute",
    hours: "Sat–Thu · 08:30 — 19:30",
    phone: "04 — 123 456",
    footer: "© Al-Drasat Institute — Taiz. On-campus enrolment.",
  },
} as const;
