export const landingDefaults = {
  ar: {
    heroKicker: "مستوى واحد في كل مرة",
    heroLine1: "تتعلّم",
    heroLine2: "بمساعدة الذكاء الإصطناعي",
    heroLine3: "وتطبّق في نفس اليوم.",
    heroDesc: "فصول 8 طلاب، مختبر يومي، ومساعد ذكاء اصطناعي يرافقك — يصحح نطقك، يراجع كودك، ويبني لك خطة مراجعة. في تعز منذ 1998، بعقل جديد.",
    ctaPrimary: "شاهد البرامج",
    ctaGhost: "جولة في الحرم →",
    micro: "التسجيل حضوري فقط · اختبار تحديد مستوى مجاني",
    programsEyebrow: "البرامج",
    programsTitle: "اختر ما تريد أن تتقنه",
    programsSub: "قائمة مفتوحة — نضيف مسارات جديدة كل فصل. كل برنامج له ورشة، مشروع، وشهادة تُتحقّق.",
    programs: [
      { id: "languages", k: "اللغات", d: "محادثة يومية ومخبر صوتي — من الحروف إلى المناظرة.", meta: "A1 → C2" },
      { id: "computing", k: "علوم الحاسب", d: "بايثون، قواعد بيانات، شبكات وويب — تبني شيئًا يعمل كل أسبوع.", meta: "12 مساقًا" },
      { id: "ai", k: "الذكاء الاصطناعي", d: "أساسيات عملية — أدوات، بيانات، ومشاريع يمكنك عرضها.", meta: "جديد" },
      { id: "diplomas", k: "الدبلومات", d: "محاسبة وإدارة وسكرتارية — حالات واقعية وملف إنجاز.", meta: "180 ساعة" },
    ],
    ateliersTitle: "الورش — حيث يحدث التعلّم",
    ateliers: [
      { k: "مختبر الصوت", v: "60 دقيقة يوميًا", p: "سماعات، تسجيل، وتصحيح نطق فوري. تتكلم أكثر مما تكتب." },
      { k: "مختبر الكود", v: "حاسوب لكل طالب", p: "بيئة حقيقية، سيرفر محلي، ومشروع يُرفع على رابط." },
      { k: "ورشة الأعمال", v: "حالات واقعية", p: "فواتير، ميزانيات، ومراسلات — كما في الشركة." },
    ],
    contactTitle: "تعال وشاهد حصة",
    address: "تعز — اليمن — معهد الدراسات",
    hours: "السبت – الخميس · 08:30 — 19:30",
    phone: "04 — 123 456",
    footer: "© معهد الدراسات — تعز. التسجيل حضوري.",
  },
  en: {
    heroKicker: "One level at a time",
    heroLine1: "Learn it",
    heroLine2: "with AI",
    heroLine3: "ship it same day.",
    heroDesc: "8 max per section, daily lab, QR-verifiable certificate — plus an AI companion that tunes your pronunciation, reviews your code, and builds your revision plan. Since 1998, now AI-forward.",
    ctaPrimary: "See programs",
    ctaGhost: "Tour campus →",
    micro: "On-campus enrolment · Free placement test",
    programsEyebrow: "Programs",
    programsTitle: "Choose what you want to master",
    programsSub: "Open list — we add tracks each term. Every program has an atelier, a project, and a verifiable certificate.",
    programs: [
      { id: "languages", k: "Languages", d: "Daily conversation & audio lab — letters to debate.", meta: "A1 → C2" },
      { id: "computing", k: "Computing", d: "Python, DB, networks & web — ship something every week.", meta: "12 courses" },
      { id: "ai", k: "Artificial Intelligence", d: "Practical AI — tools, data and projects you can demo.", meta: "New" },
      { id: "diplomas", k: "Diplomas", d: "Accounting, management, secretarial — real cases & portfolio.", meta: "180 hrs" },
    ],
    ateliersTitle: "Ateliers — where learning happens",
    ateliers: [
      { k: "Sound Lab", v: "60 min daily", p: "Headsets, recording, instant correction. You speak more than you write." },
      { k: "Code Lab", v: "1 machine per student", p: "Real env, local server, deploy link for your project." },
      { k: "Business Atelier", v: "Real cases", p: "Invoices, budgets, letters — as in a company." },
    ],
    contactTitle: "Come watch a class",
    address: "Taiz — Yemen — Al-Drasat Institute",
    hours: "Sat–Thu · 08:30 — 19:30",
    phone: "04 — 123 456",
    footer: "© Al-Drasat Institute — Taiz. On-campus enrolment.",
  },
} as const;
